//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuliusSweetland.OptiKey.StandardPlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuliusSweetland.OptiKey.StandardPlugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        public static string ALBANIAN {
            get {
                return ResourceManager.GetString("ALBANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string ARABIC {
            get {
                return ResourceManager.GetString("ARABIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenian.
        /// </summary>
        public static string ARMENIAN {
            get {
                return ResourceManager.GetString("ARMENIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        public static string AZERBAIJANI {
            get {
                return ResourceManager.GetString("AZERBAIJANI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bashkir.
        /// </summary>
        public static string BASHKIR {
            get {
                return ResourceManager.GetString("BASHKIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        public static string BELARUSIAN {
            get {
                return ResourceManager.GetString("BELARUSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string BULGARIAN {
            get {
                return ResourceManager.GetString("BULGARIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan.
        /// </summary>
        public static string CATALAN {
            get {
                return ResourceManager.GetString("CATALAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string CROATIAN {
            get {
                return ResourceManager.GetString("CROATIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string CZECH {
            get {
                return ResourceManager.GetString("CZECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string DANISH {
            get {
                return ResourceManager.GetString("DANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        public static string ESTONIAN {
            get {
                return ResourceManager.GetString("ESTONIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string FINNISH {
            get {
                return ResourceManager.GetString("FINNISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string FRENCH {
            get {
                return ResourceManager.GetString("FRENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgian.
        /// </summary>
        public static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        public static string GREEK {
            get {
                return ResourceManager.GetString("GREEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        public static string HEBREW {
            get {
                return ResourceManager.GetString("HEBREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string HUNGARIAN {
            get {
                return ResourceManager.GetString("HUNGARIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string ITALIAN {
            get {
                return ResourceManager.GetString("ITALIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazakh.
        /// </summary>
        public static string KAZAKH {
            get {
                return ResourceManager.GetString("KAZAKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        public static string LATVIAN {
            get {
                return ResourceManager.GetString("LATVIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        public static string LITHUANIAN {
            get {
                return ResourceManager.GetString("LITHUANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        public static string MACEDONIAN {
            get {
                return ResourceManager.GetString("MACEDONIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///Copyright (c) 2019 OPTIKEY LTD (UK company number 11854839) - All Rights Reserved
        ///--&gt;
        ///&lt;Plugins&gt;
        ///  &lt;Plugin&gt;
        ///    &lt;Id&gt;HttpCall&lt;/Id&gt;
        ///    &lt;Impl&gt;JuliusSweetland.OptiKey.StandardPlugins.HttpCall&lt;/Impl&gt;
        ///    &lt;Name&gt;HTTP/HTTPS Call Plugin&lt;/Name&gt;
        ///    &lt;Description&gt;This plugins enables OptiKey to call a external HTTP/HTTPS uri every time a plugin key is pressed&lt;/Description&gt;
        ///    &lt;Methods&gt;
        ///      &lt;Method&gt;
        ///        &lt;Name&gt;GET&lt;/Name&gt;
        ///        &lt;Description&gt;Calls an HTTP/H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string metadata {
            get {
                return ResourceManager.GetString("metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string NORWEGIAN {
            get {
                return ResourceManager.GetString("NORWEGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string PERSIAN {
            get {
                return ResourceManager.GetString("PERSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string POLISH {
            get {
                return ResourceManager.GetString("POLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string ROMANIAN {
            get {
                return ResourceManager.GetString("ROMANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string SERBIAN {
            get {
                return ResourceManager.GetString("SERBIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string SLOVAK {
            get {
                return ResourceManager.GetString("SLOVAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        public static string SLOVENIAN {
            get {
                return ResourceManager.GetString("SLOVENIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string SPANISH {
            get {
                return ResourceManager.GetString("SPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        public static string SWEDISH {
            get {
                return ResourceManager.GetString("SWEDISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tatar.
        /// </summary>
        public static string TATAR {
            get {
                return ResourceManager.GetString("TATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string TURKISH {
            get {
                return ResourceManager.GetString("TURKISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string UKRAINIAN {
            get {
                return ResourceManager.GetString("UKRAINIAN", resourceCulture);
            }
        }
    }
}
