//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuliusSweetland.OptiKey.StandardPlugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuliusSweetland.OptiKey.StandardPlugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a1.
        /// </summary>
        public static string ALBANIAN {
            get {
                return ResourceManager.GetString("ALBANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc2.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ab.
        /// </summary>
        public static string AZERBAIJANI {
            get {
                return ResourceManager.GetString("AZERBAIJANI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///Copyright (c) 2019 OPTIKEY LTD (UK company number 11854839) - All Rights Reserved
        ///--&gt;
        ///&lt;Plugins&gt;
        ///  &lt;Plugin&gt;
        ///    &lt;Id&gt;HttpCall&lt;/Id&gt;
        ///    &lt;Impl&gt;JuliusSweetland.OptiKey.StandardPlugins.HttpCall&lt;/Impl&gt;
        ///    &lt;Name&gt;HTTP/HTTPS Call Plugin&lt;/Name&gt;
        ///    &lt;Description&gt;This plugins enables OptiKey to call a external HTTP/HTTPS uri every time a plugin key is pressed&lt;/Description&gt;
        ///    &lt;Methods&gt;
        ///      &lt;Method&gt;
        ///        &lt;Name&gt;GET&lt;/Name&gt;
        ///        &lt;Description&gt;Calls an HTTP/H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string metadata {
            get {
                return ResourceManager.GetString("metadata", resourceCulture);
            }
        }
    }
}
