namespace JuliusSweetland.ETTA.Enums
{
    public enum FunctionKeys
    {
        Next,
        BackOne,
        BackMany,
        PreviousMatches,
        NextMatches,
        SelectMatch1,
        SelectMatch2,
        SelectMatch3,
        SelectMatch4,
        SelectMatch5,
        SelectMatch6,
        SelectMatch7,
        SelectMatch8,
        SelectMatch9,
        SelectMatch10,
        AddToDictionary,
        SkipAddingToDictionary,
        Shift,
        Enter,
        Alt,
        Ctrl,
        Tab,
        Win,
        ToggleMultiKeySelectionSupported,
        Speak,
        LettersKeyboard,
        NumbersKeyboard,
        Symbols1Keyboard,
        Symbols2Keyboard,
        MoreKeyboard
    }
}
