"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Chat\bin\Release\OptikeyChat.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Chat\bin\x64\Release\OptikeyChat.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Mouse\bin\Release\OptikeyMouse.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Mouse\bin\x64\Release\OptikeyMouse.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Pro\bin\Release\OptikeyPro.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Pro\bin\x64\Release\OptikeyPro.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Symbol\bin\Release\OptikeySymbol.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\JuliusSweetland.OptiKey.Symbol\bin\x64\Release\OptikeySymbol.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\TestControllers\bin\Release\TestControllers.exe"
"tools\signtool.exe" sign /n "Open Source Developer, Julius Sweetland" /t http://time.certum.pl /fd sha256 /v "..\src\TestControllers\bin\x64\Release\TestControllers.exe"
pause